name: Quick API Performance Check

on: [push, pull_request]

jobs:
  api-performance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Analyze API Performance
      uses: aldookware/api-performance-analyzer@v1
      with:
        code-path: '.'
        output-format: 'github'
        severity-threshold: 'medium'
